
export default new Map([
["src/content/articles/coffee-wellness/coffee-metabolism/article-1-tofu.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fcoffee-wellness%2Fcoffee-metabolism%2Farticle-1-tofu.mdx&astroContentModuleFlag=true")],
["src/content/articles/coffee-wellness/coffee-metabolism/article-2-mofu.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fcoffee-wellness%2Fcoffee-metabolism%2Farticle-2-mofu.mdx&astroContentModuleFlag=true")],
["src/content/articles/coffee-wellness/coffee-metabolism/article-3-bofu.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fcoffee-wellness%2Fcoffee-metabolism%2Farticle-3-bofu.mdx&astroContentModuleFlag=true")],
["src/content/articles/sleep-recovery/sleep-metabolism/article-1-tofu.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fsleep-recovery%2Fsleep-metabolism%2Farticle-1-tofu.mdx&astroContentModuleFlag=true")],
["src/content/articles/sleep-recovery/sleep-metabolism/article-2-mofu.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fsleep-recovery%2Fsleep-metabolism%2Farticle-2-mofu.mdx&astroContentModuleFlag=true")],
["src/content/articles/sleep-recovery/sleep-metabolism/article-3-bofu.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fsleep-recovery%2Fsleep-metabolism%2Farticle-3-bofu.mdx&astroContentModuleFlag=true")],
["src/content/pillars/coffee-wellness.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpillars%2Fcoffee-wellness.mdx&astroContentModuleFlag=true")],
["src/content/pillars/sleep-recovery.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpillars%2Fsleep-recovery.mdx&astroContentModuleFlag=true")]]);
		